# Generated by Django 6.0.2 on 2026-02-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursename',
            name='Course',
            field=models.CharField(max_length=255),
        ),
    ]
